/**
 * Regras de categorização baseadas em palavras-chave
 * Sistema híbrido de categorização automática
 */

/**
 * Mapeamento de categorias para palavras-chave
 * Baseado em padrões comuns brasileiros
 */
export const KEYWORD_RULES = {
  Moradia: [
    'aluguel',
    'condominio',
    'condomínio',
    'iptu',
    'imobiliaria',
    'imobiliária',
    'energia',
    'agua',
    'água',
    'gas',
    'gás',
    'internet',
    'luz',
    'eletropaulo',
    'enel',
    'sabesp',
    'copel',
    'cemig',
    'celesc',
    'saneamento',
    'conta de luz',
    'conta de agua',
    'conta de gás',
    'net',
    'vivo fibra',
    'claro',
    'oi fibra',
  ],

  Alimentação: [
    'mercado',
    'supermercado',
    'padaria',
    'açougue',
    'acougue',
    'ifood',
    'rappi',
    'uber eats',
    'restaurante',
    'lanchonete',
    'cafe',
    'café',
    'delivery',
    'hortifruti',
    'carrefour',
    'pao de acucar',
    'pão de açúcar',
    'extra',
    'walmart',
    'big',
    'assai',
    'atacadao',
    'atacadão',
    'dia',
    'sonda',
    'condor',
    'muffato',
    'festval',
    'angeloni',
    'comper',
    'mercadinho',
    'quitanda',
    'feira',
    'fruteira',
    'emporio',
    'empório',
    'food',
    'burger',
    'pizza',
    'pizzaria',
    'outback',
    'mcdonalds',
    "mcdonald's",
    'bk',
    'burger king',
    'giraffas',
    'subway',
    'habib',
    'habibs',
  ],

  Transporte: [
    'uber',
    '99',
    '99 pop',
    '99 taxi',
    'gasolina',
    'combustivel',
    'combustível',
    'alcool',
    'álcool',
    'diesel',
    'posto',
    'shell',
    'ipiranga',
    'br',
    'petrobras',
    'ale',
    'estacionamento',
    'zona azul',
    'pedagio',
    'pedágio',
    'onibus',
    'ônibus',
    'metro',
    'metrô',
    'trem',
    'cptm',
    'bilhete unico',
    'bilhete único',
    'rodoviaria',
    'rodoviária',
    'passagem',
    'viagem',
    'ipva',
    'dpvat',
    'licenciamento',
    'seguro auto',
    'seguro carro',
    'oficina',
    'mecanica',
    'mecânica',
    'troca de oleo',
    'óleo',
    'pneu',
    'revisao',
    'revisão',
    'vistoria',
    'taxi',
    'táxi',
    'cabify',
    'bike',
    'patinete',
    'scooter',
    'yellow',
    'tembici',
  ],

  Lazer: [
    'cinema',
    'cinepolis',
    'cinemark',
    'uci',
    'teatro',
    'show',
    'ingresso',
    'evento',
    'festa',
    'balada',
    'bar',
    'pub',
    'cerveja',
    'bebida',
    'netflix',
    'spotify',
    'youtube',
    'prime',
    'amazon prime',
    'disney',
    'disney+',
    'hbo',
    'hbo max',
    'globoplay',
    'paramount',
    'apple tv',
    'game',
    'steam',
    'playstation',
    'xbox',
    'nintendo',
    'jogos',
    'assinatura',
    'clube',
    'academia',
    'natacao',
    'natação',
    'crossfit',
    'smart fit',
    'bio ritmo',
    'esporte',
    'viagem',
    'hotel',
    'pousada',
    'airbnb',
    'booking',
    'decolar',
    'passagem aerea',
    'passagem aérea',
    'parque',
    'zoologico',
    'zoológico',
    'aquario',
    'aquário',
    'diversao',
    'diversão',
  ],

  Saúde: [
    'farmacia',
    'farmácia',
    'drogaria',
    'drogasil',
    'raia',
    'sao paulo',
    'são paulo',
    'pague menos',
    'panvel',
    'ultrafarma',
    'pacheco',
    'hospital',
    'clinica',
    'clínica',
    'consulta',
    'medico',
    'médico',
    'dentista',
    'odonto',
    'laboratorio',
    'laboratório',
    'exame',
    'raio x',
    'ultrassom',
    'tomografia',
    'ressonancia',
    'ressonância',
    'unimed',
    'amil',
    'sulamerica',
    'sulamérica',
    'bradesco saude',
    'bradesco saúde',
    'plano de saude',
    'plano de saúde',
    'convenio',
    'convênio',
    'medicamento',
    'remedio',
    'remédio',
    'terapia',
    'psicologo',
    'psicólogo',
    'fisioterapia',
    'nutricao',
    'nutrição',
    'personal',
    'vacina',
    'cirurgia',
    'internacao',
    'internação',
    'ambulancia',
    'ambulância',
    'socorrista',
    'sos',
  ],

  Educação: [
    'escola',
    'colegio',
    'colégio',
    'faculdade',
    'universidade',
    'usp',
    'unicamp',
    'unesp',
    'puc',
    'mackenzie',
    'fgv',
    'insper',
    'curso',
    'aula',
    'professor',
    'mensalidade',
    'matricula',
    'matrícula',
    'material escolar',
    'livro',
    'apostila',
    'livraria',
    'saraiva',
    'cultura',
    'nobel',
    'udemy',
    'coursera',
    'alura',
    'dio',
    'rocketseat',
    'treinamento',
    'workshop',
    'seminario',
    'seminário',
    'congresso',
    'palestra',
    'certificacao',
    'certificação',
    'pos',
    'pós',
    'mestrado',
    'doutorado',
    'mba',
    'extensao',
    'extensão',
    'idioma',
    'ingles',
    'inglês',
    'espanhol',
    'frances',
    'francês',
    'wizard',
    'ccaa',
    'cultura inglesa',
    'cultura inglesa',
    'fisk',
  ],

  Vestuário: [
    'roupa',
    'calcado',
    'calçado',
    'sapato',
    'tenis',
    'tênis',
    'camisa',
    'camiseta',
    'calca',
    'calça',
    'shorts',
    'bermuda',
    'saia',
    'vestido',
    'jaqueta',
    'casaco',
    'blusa',
    'loja',
    'magazine',
    'zara',
    'renner',
    'c&a',
    'cea',
    'riachuelo',
    'marisa',
    'hering',
    'malwee',
    'polo',
    'lacoste',
    'nike',
    'adidas',
    'puma',
    'olympikus',
    'havaianas',
    'melissa',
    'centauro',
    'decathlon',
    'netshoes',
    'dafiti',
    'tricae',
    'moda',
    'boutique',
    'shopping',
    'outlet',
    'bazar',
    'brechó',
    'brecho',
    'costura',
    'alfaiate',
    'sapataria',
    'sapateiro',
    'conserto',
  ],

  Serviços: [
    'salao',
    'salão',
    'cabeleireiro',
    'barbeiro',
    'manicure',
    'pedicure',
    'estetica',
    'estética',
    'spa',
    'massagem',
    'depilacao',
    'depilação',
    'sobrancelha',
    'maquiagem',
    'correio',
    'sedex',
    'pac',
    'encomenda',
    'cartorio',
    'cartório',
    'despachante',
    'documento',
    'advogado',
    'juridico',
    'jurídico',
    'contador',
    'contabilidade',
    'imposto',
    'taxa',
    'multa',
    'darf',
    'inss',
    'fgts',
    'seguro',
    'assistencia',
    'assistência',
    'conserto',
    'reparo',
    'eletricista',
    'encanador',
    'pedreiro',
    'pintor',
    'marceneiro',
    'serralheiro',
    'vidraceiro',
    'jardineiro',
    'faxineira',
    'diarista',
    'empregada',
    'domestica',
    'doméstica',
    'limpeza',
    'lavanderia',
    'lavagem',
    'tinturaria',
  ],

  Outros: [
    'compra',
    'pagamento',
    'transferencia',
    'transferência',
    'pix',
    'ted',
    'doc',
    'saque',
    'deposito',
    'depósito',
    'emprestimo',
    'empréstimo',
    'financiamento',
    'parcela',
    'cartao',
    'cartão',
    'fatura',
    'anuidade',
    'tarifa',
    'juros',
    'iof',
    'diversos',
    'variados',
  ],
};

/**
 * Categoriza uma transação baseada em palavras-chave
 * @param {string} description - Descrição da transação
 * @returns {object} Categoria, confiança e método
 */
export const categorizeByKeywords = description => {
  if (!description || typeof description !== 'string') {
    return {
      category: 'Outros',
      confidence: 0.3,
      method: 'default',
    };
  }

  const lowerDesc = description.toLowerCase().trim();

  // Percorre todas as categorias e suas palavras-chave
  for (const [category, keywords] of Object.entries(KEYWORD_RULES)) {
    for (const keyword of keywords) {
      if (lowerDesc.includes(keyword.toLowerCase())) {
        return {
          category,
          confidence: 0.9,
          method: 'keyword',
        };
      }
    }
  }

  // Nenhuma palavra-chave encontrada
  return {
    category: 'Outros',
    confidence: 0.3,
    method: 'default',
  };
};
